theme: minima

title: First Week on Git Hub
author: Hieu Quang
email: hquang@unm.edu
description: > # this means to ignore newlines until "baseurl:"
  First Week on Git...

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
